### ISSUE TITLE
使用帮助

### ISSUE THREAD

**Issue by CnKyo** [FlutterPlayer/fplayer#1]
您好,我使用了您的代码,但是我在设置播放速度的时候发现当设置的速度值超过1的时候播放速度没有起到作用,如果低于1时是有效的,能帮忙解答一下吗?
player.setSpeed(0.75); 有效
player.setSpeed(0.5); 有效
player.setSpeed(1.5); 无效
player.setSpeed(2.0); 无效

**Comment by 953615108** [comment]
@CnKyo 此播放器是基于fijkplayer二次开发，一些能力已经文档还未开放，可以先参考fijkplayer文档https://fijkplayer.befovy.com/docs/zh/fijkplayer-api.html

**Comment by biless** [comment]
@CnKyo 您这边是不是使用的安卓 如果是可以考虑开启 sound_touch进行倍速
