### ISSUE TITLE
求助：自行替换内核报错 Could not find :fijkplayer-full-release:.

### ISSUE THREAD

**Issue by YaoShuwei** [FlutterPlayer/fplayer#12]
![image](https://github.com/FlutterPlayer/fplayer/assets/17966298/3f35151f-f3c6-449a-9cdb-f1c3458aa077)

**Comment by YaoShuwei** [comment]
![image](https://github.com/FlutterPlayer/fplayer/assets/17966298/97cde315-689b-4d08-88e2-30037187f6ce)

**Comment by biless** [comment]
@YaoShuwei 你应该放在example目录下的Android目录

**Comment by YaoShuwei** [comment]
大佬能不能详细说下，implementation(name: 'fplayer-core', ext: 'aar')和fplayer-core.aar应该放在哪个目录，我这边试了下面的组合，都不行。感激不尽

fplayer/android/build.gradle和fplayer/android/aars

example/android/build.grade和example/android/aars

example/android/app/build.gradle和example/android/app/aars

**Comment by s451740578** [comment]
你好 我也遇到了你的这个 问题，请问你时怎么解决的呢

**Comment by BugGeeker** [comment]
> 你好 我也遇到了你的这个 问题，请问你时怎么解决的呢

看这个https://github.com/FlutterPlayer/fplayer/issues/13
