### ISSUE TITLE
io.github.flutterplayer:fplayer-core:1.1.1

### ISSUE THREAD

**Issue by GeekTR** [FlutterPlayer/fplayer#14]
这个是不是没有上传到maven仓库啊，好像下载不下来

**Comment by biless** [comment]
内核版本最高为1.0.1 应该是版本错误 现在准备修正 @zwfon

**Comment by GeekTR** [comment]
ios的也是这个版本。。。

**Comment by GeekTR** [comment]
<img width="1180" alt="image" src="https://github.com/FlutterPlayer/fplayer/assets/13369103/b216158f-5953-4eb0-b934-038060cf4ebf">
我搜到的版本只要1.0.0，是不是还没上传啊

**Comment by biless** [comment]
感谢提醒 已经重新打包 1.0.2
