### ISSUE TITLE
ios用最新版本编译不过提示如下内容

### ISSUE THREAD

**Issue by Beardemon** [FlutterPlayer/fplayer#16]
[!] CocoaPods could not find compatible versions for pod "fplayer-core":
      In snapshot (Podfile.lock):
        fplayer-core (= 1.0.0)

      In Podfile:
        fplayer (from `.symlinks/plugins/fplayer/ios`) was resolved to 0.0.1, which depends on
          fplayer-core (= 1.0.1)

**Comment by Beardemon** [comment]
版本1.0.6 1.0.7都是这个问题，1.0.4正常

**Comment by zwfon** [comment]
使用这个命令试试
pod install --repo-update

**Comment by zwfon** [comment]
如果还是不行试试1.0.8
