### ISSUE TITLE
默认头信息UA导致有的链接鉴权UA，播放失败

### ISSUE THREAD

**Issue by banchengcunluo** [FlutterPlayer/fplayer#19]
默认头信息UA导致有的链接鉴权UA，播放失败：比如这种URL
https://pcvideoaliyun.titan.mgtv.com/c1/2023/09/25_0/543A4EE36A69E9162735A0AC0FB4AB0A_20230925_1_1_1865_mp4/F249DBF45091122F065D603A4B98A661.m3u8?arange=0&pm=t3dWJMhghOCUzEf6UHD26cMCqpS4QJygVh73zAx5gwxSzLWMag634HLi5TI2CHHce79yENCk2srs8u79oip0C8XrJyutYlv1FFA3trgq1K17yNrQmU9jlR61kmHc1Vl6yDvJe9auAvk~a7MghjD3g3G8wH4MDQewWO2fXBjJrc6B6v6BYCFDYgnmMSYBKylB~wNoOOfmfGyHwOxZ0GCOwg3TaghFaUH0Rb8LoK61DsVpaQ0k3e087mXUeP76ZvzbAm9n4QhU9Ec3R5PJkl0RoCL9CwYYgu57zBTSChkTABUYY0u57tb3gcWNuWvwS7QnJ8~qRYdf3QmImHFFdarAOaz2b6y~_h7tV3YnRsh7JqYucEB6M8akPczKsH9F~XZDI16Uy72YFJhRRX0LHZAjUE01iwBRI8s3Lk7Dk~CYTEnlIPco_NqDWFOJoZjsDjxdQbrXYVCizuE-&mr=LSCYH2s2gDuT_Sl~RHcNJdZxG3FYB9LZLcXYUgMDsO52oier7an2ODfMXq0PvRRixYU3m_4JPGnuDGl8GBQd17auvqkKDewi1dei05w5M8w-&uid=c6b2b91ae86745bda8d610df6b3fe2ab&drmFlag=0&isTrial=0&scid=25021&cpno=6z23mn&ruid=313a005388064a98&sh=1

**Comment by biless** [comment]
收到您的反馈 这边建议您在初始化的时候可以使用
player.setOption(FOption.formatCategory, 'user_agent', uaStr); 方式对UA进行设置 我们这边也会根据后续的情况看是否开放成API接口进行使用
