### ISSUE TITLE
播放地址太长导致播放器播放失败

### ISSUE THREAD

**Issue by banchengcunluo** [FlutterPlayer/fplayer#24]
比如播放地址：
`https://ccp-bj29-video-preview.oss-enet.aliyuncs.com/lt/9E7E759E81D26204BF35DBC33CAC6C5215A2A58C_2284082979__sha1_bj29_db1c0424/FHD/media.m3u8?di=bj29&dr=471978182&f=653a3c4d2705fb1ebd3b47f6a690924d3cdc6930&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fMOenAlOcZ8JOnU2f5pnojONpLtpzjkTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNQTKXG%2BIqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABA7PcK4KlWaHtk8sWYeo4QBBc%2BlCMCfGmigrgfSQP%2FYOoc3laWqrso3YfJ7m4fGTGRq8fBHvSs8EW0iLXJkeSwuzVkl5gfdBL056rq0KI8AxBFuBpQQd%2FzTI1WhEVKh5UGwgWgzoeOBk6AuT6hLotX%2FPz1EvwlivsZZBLk22Cc9YgAA%3D%3D&u=9b241ee080f6477994550311f100ff99&x-oss-access-key-id=STS.NTyrSty88GQLQAHBzv4UgYYHs&x-oss-expires=1698329804&x-oss-process=hls%2Fsign%2Cparams_ZGksZHIsZix1&x-oss-signature=k3vgf3P6DJDx%2Fl5Lr8mSrjn1RumAoIoXiHE4H3TZVWk%3D&x-oss-signature-version=OSS2`

日志显示：
`D/IJKMEDIA(16693): IjkMediaPlayer_setOptionLong
I/flutter (16693): [inf] 2023-10-26 10:35:11.635324 [fijk] FijkPlayer{id:3} state changed to FijkState.initialized <= FijkState.idle
D/IJKMEDIA(16693): IjkMediaPlayer_prepareAsync
D/IJKMEDIA(16693): ijkmp_prepare_async()
E/IJKMEDIA(16693): ffp_prepare_async_l too long url
I/IJKMEDIA(16693): ===== versions =====
I/IJKMEDIA(16693): ijkplayer    : 
I/IJKMEDIA(16693): FFmpeg       : ff4.0--ijk0.8.8--20211030--926
I/IJKMEDIA(16693): libavutil    : 56.14.100
I/IJKMEDIA(16693): libavcodec   : 58.18.100
I/IJKMEDIA(16693): libavformat  : 58.12.100`

**Comment by biless** [comment]
新版本已经修复 请关注新版本
