### ISSUE TITLE
关于视频亮度调节问题

### ISSUE THREAD

**Issue by smallk1002** [FlutterPlayer/fplayer#29]
关于视频亮度调节问题

全屏的时候比如我开到最亮  缩小的时候 也会手机最亮 同理最小也是

https://github.com/FlutterPlayer/fplayer/assets/36835076/9bf7fa5c-b0cd-4b60-9850-e4278f0cb684

**Comment by zwfon** [comment]
@smallk1002 在播放器销毁时调用await ScreenBrightness().resetScreenBrightness();可以解决此问题

@override
  void dispose() async {
    super.dispose();
    try {
      await ScreenBrightness().resetScreenBrightness();
    } catch (e) {
      print(e);
      throw 'Failed to reset brightness';
    }
    player.release();
  }
