### ISSUE TITLE
使用帮助

### ISSUE THREAD

**Issue by qflbai** [FlutterPlayer/fplayer#3]
作者你好，我如何能禁用缓冲。我只想预览第一帧。无需提前缓冲后面的帧数。

**Comment by biless** [comment]
这个目前没有办法 如果是想获取第一针视频数据 肯定是需要缓冲后面的帧数 如果是仅仅是预览第一针视频 建议在上传视频时上传第一针视频图片单独存放

**Comment by qflbai** [comment]
谢谢作者解惑。
