### ISSUE TITLE
想知道本身natvie层有ijkplayer然后在flutter项目引入fplayer会有冲突怎么办

### ISSUE THREAD

**Issue by FLEasy** [FlutterPlayer/fplayer#32]
<img width="1004" alt="image" src="https://github.com/user-attachments/assets/a8d5e732-df2b-4f60-9fa3-955169c73f84">
比如这个addIjkEventListener原native层是没有的 导致播放会闪退

**Comment by biless** [comment]
内核上可能会有一些冲突,内核是重新编译过 需要在https://github.com/FlutterPlayer/fplayer/tree/master/android/src/main 目录自行改造android channel层
