### ISSUE TITLE
加载中的loading弹窗支持去掉或者修改样式吗？

### ISSUE THREAD

**Issue by WhoIsAA** [FlutterPlayer/fplayer#33]
<img width="684" alt="image" src="https://github.com/user-attachments/assets/b61af8e1-98c9-44ea-bf9c-5c92988d2834">

**Comment by zwfon** [comment]
你可以通过自定义皮肤去修改它 https://fplayer.dev/skin/custom-ui.html

**Comment by WhoIsAA** [comment]
谢谢，来信已收到，我会尽快回复你..
