### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by zhangmax94** [FlutterPlayer/fplayer#5]
很好用，就提几个issues吧
第一个:手势屏蔽靠近状态栏的地方，全屏状态下容易误触
第二个:隐藏系统的音量提示

第三个 :手势长按倍速
第四个 :分屏模式(vr)
第五个:小窗
第六个:我太菜了，可能有些功能作者已经实现了，但是我不会哈哈哈。

**Comment by biless** [comment]
@zwfon 有空评估一下 上面的功能

@zhangmax94 关于小窗模式 这个部分需要看下 小窗模式对于视屏的格式是有要求的 并不是全部的视频格式都可以支持小窗模式

**Comment by biless** [comment]
@zhangmax94 关于分屏模式 这个部分可以提供一些demo吗？我们这边没有这种体感

**Comment by zhangmax94** [comment]
> 

demo我不知道，不过我知道外观:
2d分屏:屏幕分成三个区域，分别为视频，间隔，视频,通过调节间隔宽度自己视频纵横比来修改相对大小.
3d分屏:在2d基础上  播放3d视频，可以参考360vr 播放器。https://pub.dev/packages/video_360
![Screenshot_2023-04-17-18-10-05-261_com bobo splayer](https://user-images.githubusercontent.com/44134459/232454783-eadd4b5c-5ec7-4178-87a0-a7427296eaf2.jpg)
![Screenshot_2023-04-17-18-10-01-731_com bobo splayer](https://user-images.githubusercontent.com/44134459/232454805-1da30de8-e2f3-42dd-a524-b67544604797.jpg)
![Screenshot_2023-04-17-18-09-58-465_com bobo splayer](https://user-images.githubusercontent.com/44134459/232454823-9736b607-b9d5-4ef8-8c30-f9fc49dc5e07.jpg)

**Comment by zhangmax94** [comment]
> @zwfon 有空评估一下 上面的功能
> 
> @zhangmax94 关于小窗模式 这个部分需要看下 小窗模式对于视屏的格式是有要求的 并不是全部的视频格式都可以支持小窗模式

根据视频纵横比进行等比缩放就可以吧。不过我发现，现在的操作系统都支持应用外小窗了。（redmi note10 pro miui 14）

**Comment by biless** [comment]
这个需要视频的格式要求 我们再研究一下

**Comment by zwfon** [comment]
> @zwfon 有空评估一下 上面的功能
> 
> @zhangmax94 关于小窗模式 这个部分需要看下 小窗模式对于视屏的格式是有要求的 并不是全部的视频格式都可以支持小窗模式

手势长按倍速这个已经实现了，第一个问题和第二个问题我会抽空去完善
